### ISSUE TITLE
Feature request: mock access exceptions

### ISSUE THREAD

**Issue by pliski** [ofrobots/inline-fixtures#1]
In the aim of testing my code in all conditions I would like to test the behavior of my app trying to access a directory of which it does not have the right permissions.

Is it suitable to think to allow the Fixture interface a third type? Something like:
```typescript
export interface Fixtures {
  [name: string]: string | Fixtures | WrongDir;
}
```
With WrongDir throwin EACCES (or a configurable Exception actually) at every attempt.

**Comment by ofrobots** [comment]
👍 sounds good. Let me know if you're able to contribute a PR, otherwise I can take a stab. My personal vote would be to name it `InaccessibleDir` rather than `WrongDir` as the latter doesn't sound as intuitive to me.

**Comment by pliski** [comment]
I'm taking my stab for InaccessibleFixture (can be a file or a dir) using permissions ... not sure if it will work on Win (probably not).
